// hyperNova – exporter
// Exports the project to .hcard.json and to a standalone nova64 code.js cart
import type { HyperNovaProject } from './schema';

// ---------------------------------------------------------------------------
// JSON (.hcard.json) export
// ---------------------------------------------------------------------------

export function exportToJson(project: HyperNovaProject): string {
  return JSON.stringify(project, null, 2);
}

export function downloadJson(project: HyperNovaProject): void {
  const json = exportToJson(project);
  const blob = new Blob([json], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${project.name.replace(/\s+/g, '-').toLowerCase()}.hcard.json`;
  a.click();
  URL.revokeObjectURL(url);
}

// ---------------------------------------------------------------------------
// nova64 code.js cart export
// The generated cart is a self-contained ES module that uses nova64 2D APIs
// (cls, print, rect, btn, key) to render the card stack.
// ---------------------------------------------------------------------------

export function generateCartCode(project: HyperNovaProject): string {
  const projectJson = JSON.stringify(project);

  return `// ============================================================
// Auto-generated by hyperNova – ${new Date().toISOString()}
// Project: ${project.name}
// Run this cart in the nova64 console: pnpm dev → select this cart
// ============================================================

const _project = ${projectJson};

// Runtime state
let _currentCardId = _project.stacks[0]?.cards[0]?.id ?? '';
let _fieldValues = {};
let _frameClickHandled = false;

// ---- Boot ------------------------------------------------------------------
export function init() {
  setCameraPosition(0, 0, 5);
  setAmbientLight(0xffffff, 1);
  _currentCardId = _project.stacks[0]?.cards[0]?.id ?? '';
}

// ---- Per-frame -------------------------------------------------------------
export function update(_dt) {
  _frameClickHandled = false;
}

// ---- Render ----------------------------------------------------------------
export function draw() {
  const card = _findCard(_currentCardId);
  if (!card) { print('No card found', 10, 10, 0xff0000); return; }

  // Background
  const bg = card.background;
  const bgColor = _hexToNum(bg.color ?? '#f8f4ee');
  cls(bgColor);

  // Objects
  for (const obj of card.objects) {
    switch (obj.type) {
      case 'rect': {
        const c = _hexToNum(obj.bgColor);
        rect(obj.x, obj.y, obj.width, obj.height, c);
        break;
      }
      case 'text': {
        const c = _hexToNum(obj.color);
        const lines = obj.text.split('\\n');
        lines.forEach((line, i) => {
          print(line, obj.x, obj.y + i * (obj.fontSize + 2), c);
        });
        break;
      }
      case 'button': {
        const bc = _hexToNum(obj.bgColor);
        const tc = _hexToNum(obj.textColor);
        rect(obj.x, obj.y, obj.width, obj.height, bc);
        print(obj.label, obj.x + 8, obj.y + Math.floor((obj.height - 8) / 2), tc);
        // Simple btn(0) click anywhere → run first button found
        if (btn(4) && !_frameClickHandled) {
          _frameClickHandled = true;
          _runScript(obj.script);
        }
        break;
      }
      case 'field': {
        rect(obj.x, obj.y, obj.width, obj.height, 0xffffff);
        const val = _fieldValues[obj.id] ?? obj.value ?? '';
        print(val || obj.placeholder, obj.x + 4, obj.y + 8, 0x333333);
        break;
      }
    }
  }
}

// ---- Helpers ---------------------------------------------------------------
function _findCard(id) {
  for (const stack of _project.stacks) {
    const c = stack.cards.find(c => c.id === id);
    if (c) return c;
  }
  return null;
}

function _hexToNum(hex) {
  return parseInt((hex ?? '#888888').replace('#', ''), 16);
}

function _runScript(script) {
  if (!script) return;
  try {
    const fn = new Function(
      'goToCard', 'goNext', 'goPrev', 'goFirst', 'goLast',
      'setField', 'getField', 'log',
      '"use strict";\\n' + script
    );
    fn(
      (id) => { _currentCardId = id; },
      () => { const c = _nav(1); if (c) _currentCardId = c; },
      () => { const c = _nav(-1); if (c) _currentCardId = c; },
      () => { const c = _project.stacks[0]?.cards[0]; if (c) _currentCardId = c.id; },
      () => { const s = _project.stacks[0]; if (s) _currentCardId = s.cards[s.cards.length-1].id; },
      (id, val) => { _fieldValues[id] = val; },
      (id) => _fieldValues[id] ?? '',
      (...a) => console.log('[cart]', ...a)
    );
  } catch(e) { console.warn('[cart] script error', e); }
}

function _nav(delta) {
  for (const stack of _project.stacks) {
    const idx = stack.cards.findIndex(c => c.id === _currentCardId);
    if (idx !== -1) return stack.cards[idx + delta]?.id ?? null;
  }
  return null;
}
`;
}

export function downloadCart(project: HyperNovaProject): void {
  const code = generateCartCode(project);
  const blob = new Blob([code], { type: 'text/javascript' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${project.name.replace(/\s+/g, '-').toLowerCase()}-cart.js`;
  a.click();
  URL.revokeObjectURL(url);
}
