LIBRETRO_COMM_DIR := $(CORE_DIR)
QUICKJS_DIR := $(CORE_DIR)/../nova64-godot/gdextension/third_party/quickjs
INCFLAGS := -I$(LIBRETRO_COMM_DIR) -I$(QUICKJS_DIR)

SOURCES_C := \
	$(CORE_DIR)/nova64_libretro.c \
	$(QUICKJS_DIR)/quickjs.c \
	$(QUICKJS_DIR)/libregexp.c \
	$(QUICKJS_DIR)/libunicode.c \
	$(QUICKJS_DIR)/dtoa.c

CFLAGS += $(INCFLAGS) -D_GNU_SOURCE -DCONFIG_VERSION=\"nova64-libretro\"
CFLAGS += -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unused-but-set-variable
LIBM += -lm -lz

ifneq (,$(findstring msvc2003,$(platform)))
INCFLAGS += -I$(LIBRETRO_COMM_DIR)/include/compat/msvc
endif
