#!/usr/bin/env python3
"""gen_api_ref.py — auto-generate a Markdown API reference from nova64_libretro.c.

Scans for set_function() registration calls and emits a table of JS API names,
their argument counts, and the C handler they map to.

Usage:
    python3 retroarch/tests/gen_api_ref.py > retroarch/API_REFERENCE.md
"""
import re
import sys
import os

SRC = os.path.join(os.path.dirname(__file__), "..", "nova64_libretro.c")

# Match: set_function(ctx, <ns>, "<name>", <handler>, <argc>)
CALL_RE = re.compile(
    r'set_function\s*\(\s*ctx\s*,\s*(\w+)\s*,\s*"([^"]+)"\s*,\s*(\w+)\s*,\s*(\d+)\s*\)'
)

# Map variable names → namespace labels
NS_LABELS = {
    "global":   "(global)",
    "nova64":   "nova64",
    "draw":     "nova64.draw",
    "input":    "nova64.input",
    "scene":    "nova64.scene",
    "camera":   "nova64.camera",
    "light":    "nova64.light / nova64.lights",
    "audio":    "nova64.audio",
    "assets":   "nova64.assets",
    "storage":  "nova64.storage",
    "post":     "nova64.post",
    "meta":     "nova64.meta",
    "perf":     "nova64.perf",
    "tilemap":  "nova64.tilemap",
    "sprites":  "nova64.sprites",
    "random":   "nova64.random",
    "phys":     "nova64.physics",
    "con":      "nova64.console",
    "cheevos":  "nova64.cheevos",
    "sc":       "nova64.scene (alias)",
}

def handler_to_summary(handler: str) -> str:
    """Best-effort: strip js_ prefix and convert snake_case to readable text."""
    name = handler.removeprefix("js_")
    return name.replace("_", " ")

def main():
    with open(SRC, encoding="utf-8") as f:
        src = f.read()

    entries = []
    for m in CALL_RE.finditer(src):
        ns_var, fn_name, handler, argc = m.group(1), m.group(2), m.group(3), int(m.group(4))
        ns_label = NS_LABELS.get(ns_var, ns_var)
        entries.append((ns_label, fn_name, argc, handler))

    # Deduplicate: same namespace+name keeps first occurrence
    seen = set()
    unique = []
    for e in entries:
        key = (e[0], e[1])
        if key not in seen:
            seen.add(key)
            unique.append(e)

    # Group by namespace
    from collections import defaultdict
    groups = defaultdict(list)
    for ns, fn, argc, handler in unique:
        groups[ns].append((fn, argc, handler))

    print("# Nova64 RetroArch — JS API Reference")
    print()
    print("> Auto-generated by `retroarch/tests/gen_api_ref.py` — do not edit by hand.")
    print()

    NS_ORDER = [
        "(global)", "nova64", "nova64.draw", "nova64.input", "nova64.scene",
        "nova64.scene (alias)", "nova64.camera", "nova64.light / nova64.lights",
        "nova64.audio", "nova64.assets", "nova64.storage", "nova64.post",
        "nova64.meta", "nova64.perf", "nova64.tilemap", "nova64.sprites",
        "nova64.random", "nova64.physics", "nova64.console", "nova64.cheevos",
    ]

    all_ns = NS_ORDER + sorted(k for k in groups if k not in NS_ORDER)

    for ns in all_ns:
        if ns not in groups:
            continue
        fns = sorted(groups[ns], key=lambda x: x[0])
        print(f"## `{ns}`")
        print()
        print("| Function | Args | C handler |")
        print("|---|---|---|")
        for fn, argc, handler in fns:
            print(f"| `{fn}` | {argc} | `{handler}` |")
        print()

if __name__ == "__main__":
    main()
